plugins {
    id 'com.enonic.xp.app'
    id 'com.enonic.defaults' version '2.1.6'
    id 'maven-publish'
}

dependencies {
    implementation xplibs.api.script
    include xplibs.content
    include xplibs.portal
    include xplibs.io
    include(libs.lib.http.client)
    include(libs.lib.google.cse) {
        exclude group: 'com.enonic.xp'
    }
    include libs.lib.thymeleaf
    include libs.lib.util
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo('dev')
}
